# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d9332579a45e4b0b2de3b8a99d01cb0165fbb91eb6f91ec1538f15ec7e1b60387986f4967dcdcfb3f4ea1716a9bb77c92f89446e3829f831d1a7b88a6589ce

test:
  secret_key_base: 427a96f901ffcbc56af1ac27772639d881bb6fbebbd308df8262bdfaf7b3c974c5b17d5cf5b309fdf098e3243162d00d16ccd798f33c58f9298c1f206608ecc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
